### ISSUE TITLE
The dataset's uploading plan

### ISSUE THREAD

**Issue by softword-tt** [booker-max/Unsupervised-Deraining-with-Event-Camera#1]
Hi, thx for your awesome work!
I was wondering when it would be convenient to upload the dataset. Looking forward to your reply！:D

**Comment by booker-max** [comment]
Hello, I've been busy with some graduation-related matters recently. I'll be able to upload the dataset in June. Thank you for your understanding.

**Comment by Yee-Sing** [comment]
> Hello, I've been busy with some graduation-related matters recently. I'll be able to upload the dataset in June. Thank you for your understanding.

We are excited to look forward to the subsequent releases.

**Comment by softword-tt** [comment]
> Hello, I've been busy with some graduation-related matters recently. I'll be able to upload the dataset in June. Thank you for your understanding.

Thank you for your reply. I'm really excited for future releases!

**Comment by booker-max** [comment]
Sorry for the delay again. The data set is currently being uploaded to the network disk and requires a larger space. It will take a few more days. Thank you.

**Comment by softword-tt** [comment]
> Sorry for the delay again. The data set is currently being uploaded to the network disk and requires a larger space. It will take a few more days. Thank you.

Sure, I get it, but I'd really appreciate it if you could do it as soon as you can. Thanks a lot!

**Comment by liujiaocv** [comment]
I also look forward to the author uploading the dataset
